### ISSUE TITLE
Microsoft SQL platform problems with DATE & TIME types.  

### ISSUE THREAD

**Issue by jhaisley** [propelorm/Propel2#1265]
The Microsoft SQL platform file currently results in errors when writing a date or time field (but not DATETIME, those are working fine).  

"[S0001][241] Conversion failed when converting date and/or time from character string."

PR #1250 fixes this issue.

**Comment by mhaisley** [comment]
Resolved by merging PR 1250

**Comment by MDT-FGI** [comment]
I just updated to Master and double-checked, that your fix is present. Then I rebuilt everything and migrated, just to be sure. And it does not seem to be working.

I still get the error:
"Conversion failed when converting date and/or time from character string."

Samplecode is very easy:
`class Note extends BaseNote
{
    public static function createNewNote()
    {
        $Note = new Note();
        $Note->setValue("TEST");
        $Note->save();
    }
}`
DB table with fields (ID, Value) and behaviour "timestampable" on MSSQL.

Did I forget something? Please anybody confirm.

**Comment by mhaisley** [comment]
That seems problematic.  I don't use the timestampable behavior in my current applications, so I've not tested that scenario. Do you have debug logs? If not can you turn debugging on and add the insert statement from your example above?

**Comment by MDT-FGI** [comment]
I have set up MonoLog and all corresponding debug stuff in the config but there is no additional output for that specific query.

> 'defaultLogger' => [
>                     'type' => 'stream',
>                     'path' => 'H:\htdocs\vendor\propel\propel.log',
>                     'level' => 100
>                 ]

Output:
> [2016-10-21 14:00:20] defaultLogger.ERROR: SQLSTATE[22007]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. [] []

There is just two SELECTS before that error and they are for loading the page and have nothing to do with timestamps or anything.
No INSERTs are shown.

I also tried to set the debug on the specific query but that didn't output anything neither. So I tried to output the query myself with some rudimentary debug-output:
> INSERT INTO [Note] (value,ObjectUID,created_at,updated_at) VALUES (:p1,:p2,:p3,:p4)
> 
> Array (
> 	[0] => Array (
> 		[column] => value
> 		[table] => Note
> 		[value] => TEST )
> 	[1] => Array (
> 		[column] => ObjectUID
> 		[table] => Note
> 		[value] => 543 )
> 	[2] => Array (
> 		[column] => created_at
> 		[table] => Note
> 		[value] => DateTime Object (
> 					[date] => 2016-10-21 14:15:00.986604
> 					[timezone_type] => 3
> 					[timezone] => Europe/Berlin
> 					)
> 				)
> 	[3] => Array (
> 		[column] => updated_at
> 		[table] => Note
> 		[value] => DateTime Object (
> 					[date] => 2016-10-21 14:15:00.986604
> 					[timezone_type] => 3
> 					[timezone] => Europe/Berlin
> 					)
> 				)
> )

I hope this helps. Otherwise just give me a hint how to provide better information.

**Comment by MDT-FGI** [comment]
I think I got at least the problem with the statement now. After another investigation I echoed the statement right before execution.
This is what came up:
> [:p1] => 'TEST'
> [:p2] => 543
> [:p3] => '2016-10-21 15:28:01.416627'
> [:p4] => '2016-10-21 15:28:01.416627' )
> 
> [sql:protected] => INSERT INTO [Note] (value,garm_ObjectUID,created_at,updated_at) VALUES (:p1,:p2,:p3,:p4)

When trying the INSERT in the SQL Management  Studio, I came to the conclusion that the problem is the last three digits.
Where the following INSERT is failing:
> INSERT INTO [Note] (value,garm_ObjectUID,created_at,updated_at) VALUES ('TEST',543,'2016-10-21 15:28:01.416627','2016-10-21 15:28:01.416627')

THIS one works like a charm:
> INSERT INTO [Note] (value,ObjectUID,created_at,updated_at) VALUES ('TEST',543,'2016-10-21 15:28:01.416','2016-10-21 15:28:01.416')

I hope this is what you need to know to fix the issue.

**Comment by MDT-FGI** [comment]
According to this discussion on stackoverflow ( -> http://stackoverflow.com/questions/19025192/convert-varchar-to-datetime-in-sql-which-is-having-millisec ) , you can use the Type DATETIME2 in MSSQL Server 2008 R2 and above.
This allows you to store 6 digits of milliseconds.

The other way round you would need to cut the last 3 digits off the Datetime given to the MSSQL-database.

Choose which one you like better :-) I tested either way and both solutions work. I am not that into this project to start a pull request on my own.

**Comment by KoffeinKaio** [comment]
Same problem here, also specifing 'defaultTimeStampFormat' in the configuration doesnt change anything.

**Comment by MDT-FGI** [comment]
Thanks for your comment, KoffeinKaio.

Your workaround seems to be much better and less time consuming.
But where exactly do you place that override?

Normally you would put that in the "<column ...>"-tag, but since we are using the "<behavior name="timestampable" />" there is no explicit column.
Can you just put it in the "<behaviour>"-tag, too?

**Comment by KoffeinKaio** [comment]
Put it in your database definition (schema.xml).
` 
<?xml version="1.0" encoding="UTF-8"?>
<database name="testDB" defaultIdMethod="native">
   <table name="testTable">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true"/>
        <column name="dateval" type="timestamp" sqlType="datetime2"/>
    </table>
</database>
`

**Comment by jhaisley** [comment]
I submitted a pull request to move over to DATETIME2 in order to resolve the issues with timestamps.

**Comment by MDT-FGI** [comment]
It's pull request #1293 just for the records :+1:

**Comment by jhaisley** [comment]
Thanks for bringing this up @MDT-FGI as I mentioned before I'm not using timestampable so it's never impacted me, but I'm all for fixing all of our SQL server bugs.
